### ISSUE TITLE
Dockerise this?

### ISSUE THREAD

**Issue by Crashthatch** [assaflavie/runlike#3]
Would it be possible to dockerise this application?

It sounds really useful, but I can't go around installing python & pip on our production boxes. But if it were available as a container I could pull that & run it inside docker.

I'm guessing it would need the docker socket to be mounted to give it access to the docker server? Or it could accept JSON piped from docker inspect via the cli and then output the reverse-engineered docker run command and exit.

`$ docker inspect my_running_ctr | docker run assaflavie/runlike`

Am I missing anything / are there other reasons that this wouldn't work?

**Comment by assaflavie** [comment]
It'll work. I don't like mounting the docker socket on containers in general... but if you can't get python/pip on your servers, that's probably the way to go. It would be a 3 line Dockerfile basically...

But, also, this hasn't been updated in a while, so trust but verify (especially if you're using relatively recent docker features). Currently it knows the most basic docker flags (the ones that have been around for ~ 2 years), like port publishing, volumes, etc.

I should really get around to updating this.

**Comment by assaflavie** [comment]
I've pushed this as an image now.
So you can do something like:
```
docker run \
    -v /var/run/docker.sock:/var/run/docker.sock \
    assaflavie/runlike -p SOME-CONTAINER
```
